nowe teksty
brun0ne/ktopytal.info pull request #1
Opened 2022-11-17 20:00 UTC by wetraks

2022-11-17 23:31 UTC, sefinek24 commented
Przy okazji mogłeś to wywalić
"Szukanie eksperta w tej dziedzinie na TikToku..."

bo tiktok to szambo + syf

2022-11-18 15:49 UTC, wetraks commented
Zrobione

2023-04-10 22:49 UTC, brun0ne requested changes
`Szukanie eksperta w tej dziedzinie na TikToku...` musi zostać, gdyby nie tiktok to nikt by o tej stronce nie usłyszał 😅

Nie rozbijałbym tekstów na dwie tablice, z każdą kolejną będzie się robił większy bałagan, nie ma nic złego w dodawaniu nowych do obecnej.

Widzę literówkę w słowie `nielegalnnych`.
Co do `amogus`, wolę żeby ta strona nie promowała konkretnych discordów itp.

2023-04-10 22:54 UTC, sefinek24 commented
no nie wiem, i tak się o niej dowiedziałem bodajże z discorda.

jeśli chodzi o rozbijanie tego na dwie tablice, fakt.

swoją drogą, dlaczego napisałeś tę strone korzystając z znaczników HTML4 w niektórych miejscach? Te `<br />` troche boli w oczy

2023-04-10 23:11 UTC, brun0ne commented
Racja, możliwe że je zmienię, nie było innego powodu niż stare przyzwyczajenia

2023-04-10 23:12 UTC, sefinek commented
luz

2023-04-11 00:43 UTC, sefinek24 commented
jestem ciekaw jak chatgpt by "polepszył" ten kod

2023-04-11 00:48 UTC, merged